Repository sigstore/sigstore-python, pull requests merged in 2022-04, with the labels that each got.

#36 Implement Signed Entry Timestamp (SET) verification
  setup.py
  sigstore/_internal/rekor/_client.py
  sigstore/_internal/set.py
  sigstore/_store/rekor.pub
  sigstore/_verify.py
Labels: component:verification

#43 README: fill in details
  .github/workflows/ci.yml
  CONTRIBUTING.md
  Makefile
  README.md
  setup.py
Labels: documentation

#53 Implement Bandit CI Tests
  .bandit.yaml
  .github/workflows/ci.yml
  setup.py
Labels: qa, component:cicd

#54 sigstore: prevent unintended I/O side effects
  sigstore/_cli.py
  sigstore/_sign.py
  sigstore/_verify.py
Labels: bug, component:cli

#47 github/workflows: add release workflow
  .github/workflows/release.yml
Labels: component:cicd

#59 internal/oidc, test: ambient credentials, refactoring
  sigstore/_cli.py
  sigstore/_internal/oidc/__init__.py
  sigstore/_internal/oidc/ambient.py
  sigstore/_internal/oidc/oauth.py
  test/internal/__init__.py
  test/internal/oidc/__init__.py
  test/internal/oidc/test_ambient.py
Labels: enhancement, component:signing
