Repository sigstore/sigstore-python, pull requests merged in 2022-05, with the labels that each got.

#63 setup: use importlib instead of exec
  setup.py
  sigstore/__init__.py
  sigstore/_cli.py
  test/test_sign.py
  test/test_verify.py
Labels: enhancement

#65 Refactor: add logging, better isolate output
  sigstore/_cli.py
  sigstore/_sign.py
  test/test_sign.py
Labels: refactoring

#68 cli: add a flag for disabling ambient OIDC detection
  README.md
  sigstore/_cli.py
Labels: component:cli

#70 build: move almost everything to pyproject.toml
  .github/workflows/ci.yml
  Makefile
  pyproject.toml
  setup.py
Labels: refactoring

#71 cli, verify: refactor, add logging
  mypy.ini
  sigstore/_cli.py
  sigstore/_verify.py
  test/test_verify.py
Labels: component:cli, component:verification, refactoring

#79 sigstore, README: add `--version` flag
  README.md
  sigstore/_cli.py
Labels: component:cli

#83 workflows/release: smoke-test each distribution
  .github/workflows/release.yml
Labels: qa, component:cicd

#85 treewide: ratchet down typing, move mypy config to pyproject
  Makefile
  mypy.ini
  pyproject.toml
  sigstore/_cli.py
  sigstore/_internal/fulcio/_client.py
  sigstore/_internal/oidc/oauth.py
  sigstore/_internal/rekor/_client.py
  sigstore/_internal/set.py
  sigstore/_verify.py
Labels: qa, refactoring

#86 bandit: merge config into pyproject
  .bandit.yaml
  .github/workflows/ci.yml
  CONTRIBUTING.md
  Makefile
  pyproject.toml
Labels: qa, component:cicd

#89 oidc/ambient: constrain nosec
  sigstore/_internal/oidc/ambient.py
Labels: qa

#91 Support Google Cloud impersonation
  README.md
  cloudbuild.yaml
  sigstore/_internal/oidc/ambient.py
  test/internal/oidc/test_ambient.py
Labels: component:signing

#98 oidc/ambient: Google: fail softly if the SMBIOS product name doesn't match
  sigstore/_internal/oidc/ambient.py
  test/internal/oidc/test_ambient.py
Labels: component:signing
