Repository sigstore/sigstore-python, pull requests merged in 2022-08, with the labels that each got.

#176 Bump to 0.6.3
  README.md
  sigstore/__init__.py
Labels: chore

#179 pyproject, ci: use recursive extras
  .github/workflows/ci.yml
  Makefile
  pyproject.toml
Labels: component:cicd

#180 test: add an "online" marker for online tests
  .github/workflows/ci.yml
  test/conftest.py
  test/test_verify.py
Labels: component:tests

#178 ✨ Enable Scorecard badge
  .github/workflows/scorecards-analysis.yml
  README.md
Labels: qa

#185 ci: add debug loglevel to ci and debug log of verified log index
  .github/workflows/staging-tests.yml
  sigstore/_verify.py
Labels: component:cicd, component:tests
