Repository sigstore/sigstore-python, pull requests merged in 2022-12, with the labels that each got.

#329 sigstore: stream input into signing
  sigstore/_cli.py
  sigstore/_sign.py
  sigstore/_utils.py
  sigstore/_verify/models.py
  sigstore/_verify/verifier.py
  test/unit/conftest.py
  test/unit/test_sign.py
  test/unit/test_utils.py
Labels: component:signing, component:verification

#332 Add a CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#336 test: avoid pre-computing large strings in parametrized tests
  test/unit/internal/test_sct.py
Labels: component:tests

#334 Run tests in CI with full verbosity
  .github/workflows/ci.yml
Labels: component:cicd

#341 Eliminate deprecation warnings on 3.11
  .github/workflows/ci.yml
  pyproject.toml
  sigstore/_cli.py
  sigstore/_internal/ctfe.py
  sigstore/_internal/rekor/client.py
  sigstore/_utils.py
  sigstore/_verify/verifier.py
  test/unit/test_store.py
Labels: refactoring, chore

#344 Chore: More docs
  sigstore/_internal/oidc/__init__.py
  sigstore/_internal/oidc/ambient.py
  sigstore/_internal/oidc/issuer.py
  sigstore/_sign.py
  sigstore/_utils.py
  test/unit/internal/oidc/test_ambient.py
Labels: documentation

#346 TASK(jl): increase code coverage.
  test/unit/internal/oidc/test_ambient.py
  test/unit/internal/oidc/test_issuer.py
  test/unit/internal/test_ctfe.py
  test/unit/verify/test_policy.py
Labels: component:tests

#342 workflows/conformance: bump sigstore-conformance action
  .github/workflows/conformance.yml
Labels: component:cicd, component:tests, safe to test

#345 Chore: more docs
  pyproject.toml
  sigstore/_internal/__init__.py
  sigstore/_internal/ctfe.py
  sigstore/_internal/merkle.py
  sigstore/_internal/sct.py
  sigstore/_internal/set.py
  sigstore/_store/__init__.py
  sigstore/_verify/models.py
  sigstore/_verify/policy.py
  sigstore/_verify/verifier.py
Labels: documentation, chore

#353 treewide: remove flake8, add ruff
  .flake8
  .github/workflows/ci.yml
  CONTRIBUTING.md
  Makefile
  pyproject.toml
  sigstore/_utils.py
Labels: qa, chore, safe to test

#350 docs: more docstring coverage
  sigstore/_internal/oidc/oauth.py
  sigstore/_internal/rekor/client.py
Labels: documentation, safe to test

#351 Use TUF to download key/cert material
  .gitignore
  README.md
  pyproject.toml
  sigstore/_cli.py
  sigstore/_internal/ctfe.py
  sigstore/_internal/rekor/client.py
  sigstore/_internal/tuf.py
  sigstore/_sign.py
  sigstore/_store/__init__.py
  sigstore/_store/ctfe.pub
  sigstore/_store/ctfe_2022.pub
  sigstore/_store/fulcio.crt.pem
  sigstore/_store/fulcio_intermediate.crt.pem
  sigstore/_store/rekor.pub
  sigstore/_store/root.json
  sigstore/_store/staging-root.json
  sigstore/_verify/verifier.py
  test/unit/assets/staging-tuf/1.root.json
  test/unit/assets/staging-tuf/ctfe.pub
  test/unit/assets/staging-tuf/ctfe_2022.pub
  test/unit/assets/staging-tuf/ctfe_2022_2.pub
  test/unit/assets/staging-tuf/fulcio.crt.pem
  test/unit/assets/staging-tuf/fulcio_intermediate.crt.pem
  test/unit/assets/staging-tuf/rekor.pub
  test/unit/assets/staging-tuf/snapshot.json
  test/unit/assets/staging-tuf/targets.json
  test/unit/assets/staging-tuf/timestamp.json
  test/unit/conftest.py
  test/unit/internal/test_ctfe.py
  test/unit/internal/test_tuf.py
  test/unit/test_sign.py
  test/unit/test_store.py
  test/unit/verify/test_models.py
  test/unit/verify/test_verifier.py
Labels: component:signing, component:verification

#364 Prep 0.9.0
  CHANGELOG.md
  sigstore/__init__.py
Labels: chore

#367 Makefile, sigstore: round out doc coverage, enable interrogate
  Makefile
  sigstore/_internal/fulcio/client.py
  sigstore/_internal/tuf.py
Labels: documentation, qa, safe to test

#366 Miscellaneous cleanup
  README.md
  test/unit/test_sign.py
Labels: chore, safe to test

#369 tuf: intrinsic types, use `urljoin`
  sigstore/_internal/tuf.py
Labels: chore

#372 _cli: refactor logging behavior
  CHANGELOG.md
  README.md
  sigstore/_cli.py
Labels: component:cli, refactoring, safe to test

#373 _internal/tuf: restructure TUF cache dir layout
  sigstore/_internal/tuf.py
Labels: refactoring, safe to test, component:tuf
