Repository sigstore/sigstore-python, pull requests merged in 2022-10, with the labels that each got.

#227 README: update GitHub Action slugs
  README.md
Labels: documentation, chore

#228 Update CONTRIBUTING.md to expose the requirements to open a PR. Closes #224
  .github/pull_request_template.md
  CONTRIBUTING.md
Labels: documentation

#233 ci, Makefile: make `check-readme` a make target
  .github/workflows/ci.yml
  Makefile
Labels: component:cicd

#234 Makefile: run recursive make silently
  Makefile
Labels: component:cicd

#235 Tests: ensure consistency of transparency log response and entry
  .github/workflows/ci.yml
  sigstore/_internal/rekor/client.py
  sigstore/_verify.py
  test/test_sign.py
Labels: component:tests

#202 Staging workflow improvements
  .github/workflows/staging-tests.yml
Labels: component:cicd

#238 rekor, verify: replace unstable API use
  sigstore/_internal/rekor/client.py
  sigstore/_verify.py
Labels: component:verification

#241 _verify: make the failure reason more detailed when rekor lookup fails
  sigstore/_cli.py
  sigstore/_verify.py
Labels: component:verification

#242 _cli: add envvar defaults for most options
  sigstore/_cli.py
Labels: component:cli

#243 sigstore: 0.6.7
  sigstore/__init__.py
Labels: chore

#244 _cli: add boolean envvar defaults
  README.md
  sigstore/_cli.py
Labels: component:cli

#259 test: add an `ambient_oidc` marker
  test/conftest.py
  test/test_sign.py
Labels: component:cicd, component:tests

#270 fix deprecated set-output
  .github/workflows/release.yml
Labels: component:cicd

#267 sigstore: add a CT keyring, use it for SCT verification
  sigstore/_cli.py
  sigstore/_internal/ctfe.py
  sigstore/_internal/rekor/client.py
  sigstore/_internal/sct.py
  sigstore/_sign.py
  sigstore/_store/ctfe_2022.pub
  sigstore/_utils.py
  test/internal/test_ctfe.py
  test/internal/test_sct.py
  test/test_utils.py
Labels: component:signing, component:verification

#284 sigstore: 0.6.8
  sigstore/__init__.py
Labels: chore

#286 workflows/ci: add Python 3.11 to matrix
  .github/workflows/ci.yml
  pyproject.toml
Labels: component:cicd, chore
