Repository sigstore/sigstore-python, pull requests merged in 2023-02, with the labels that each got.

#474 NewTypes for clearer encoding types
  sigstore/_cli.py
  sigstore/_internal/ctfe.py
  sigstore/_internal/fulcio/client.py
  sigstore/_internal/merkle.py
  sigstore/_internal/oidc/oauth.py
  sigstore/_internal/rekor/client.py
  sigstore/_internal/sct.py
  sigstore/_utils.py
  sigstore/sign.py
  sigstore/transparency.py
  sigstore/verify/models.py
  sigstore/verify/verifier.py
Labels: refactoring, safe to test

#507 Use DEFAULT_AUDIENCE instead of hard-coding
  sigstore/_internal/oidc/ambient.py
Labels: safe to test

#508 chore: rename some error types
  sigstore/_internal/sct.py
  sigstore/_internal/set.py
  sigstore/verify/verifier.py
  test/unit/test_sign.py
Labels: refactoring, chore, safe to test
