Repository sigstore/sigstore-python, pull requests merged in 2023-03, with the labels that each got.

#521 Add CI to test install-ability of `requirements.txt` file
  .github/workflows/requirements.yml
  install/.python-version
  install/requirements.txt
Labels: safe to test

#523 sigstore: 1.1.0rc1
  sigstore/__init__.py
Labels: chore, safe to test

#530 MyPy 1.1, fixes
  pyproject.toml
  sigstore/verify/models.py
  sigstore/verify/verifier.py
Labels: qa, chore, safe to test

#536 verify: Stop using `pydantic` aliases in constructor to avoid `mypy` plugin bug
  sigstore/verify/models.py
Labels: component:cicd, safe to test

#535 treewide: Replace ambient credential detection with `id`
  CHANGELOG.md
  README.md
  pyproject.toml
  sigstore/_cli.py
  sigstore/_internal/oidc/__init__.py
  sigstore/_internal/oidc/ambient.py
  sigstore/_internal/oidc/oauth.py
  sigstore/oidc.py
  test/unit/conftest.py
  test/unit/internal/oidc/test_ambient.py
  test/unit/internal/oidc/test_issuer.py
  test/unit/test_sign.py
Labels: component:signing, dependencies, safe to test

#531 Move all error diagnostics to _errors
  CHANGELOG.md
  sigstore/_cli.py
  sigstore/_internal/sct.py
  sigstore/_internal/tuf.py
  sigstore/errors.py
  sigstore/oidc.py
  test/unit/internal/oidc/test_issuer.py
Labels: refactoring

#548 Pin requirements on releases with a workflow
  .github/dependabot.yml
  .github/workflows/pin-requirements.yml
  .github/workflows/release.yml
Labels: component:cicd, safe to test

#557 sigstore: 1.1.2rc1
  sigstore/__init__.py
Labels: chore, safe to test

#558 workflows/pin-requirements: typo
  .github/workflows/pin-requirements.yml
Labels: github_actions, safe to test

#560 workflows/pin-requirements: fix interpolation
  .github/workflows/pin-requirements.yml
Labels: github_actions, safe to test

#562 pin-requirements: fix wheel URL
  .github/workflows/pin-requirements.yml
Labels: component:cicd, safe to test

#566 workflows/release: use OIDC for publishing
  .github/workflows/release.yml
Labels: component:cicd, chore, safe to test

#555 sct, keyring: specialize errors
  CHANGELOG.md
  sigstore/_internal/keyring.py
  sigstore/_internal/sct.py
Labels: component:api, safe to test

#571 sigstore, test: reflow, fix
  sigstore/_internal/sct.py
  test/unit/test_sign.py
Labels: component:tests, safe to test

#572 `pin-requirements` workflow self-test
  .github/workflows/pin-requirements.yml
  .github/workflows/requirements.yml
Labels: component:cicd, safe to test

#573 workflows/pin-requirements: fix job name
  .github/workflows/pin-requirements.yml
Labels: component:cicd, github_actions, safe to test

#576 Adapt ambient OIDC tests to support interactive flow for local testing
  .github/workflows/ci.yml
  CHANGELOG.md
  CONTRIBUTING.md
  Makefile
  sigstore/oidc.py
  test/unit/conftest.py
  test/unit/test_sign.py
Labels: component:tests, safe to test

#542 tuf: use bundled trusted root if available
  CHANGELOG.md
  sigstore/_internal/keyring.py
  sigstore/_internal/tuf.py
  sigstore/_utils.py
  test/unit/internal/test_tuf.py
  test/unit/test_utils.py
Labels: safe to test, component:tuf
