Repository sigstore/sigstore-python, pull requests merged in 2023-01, with the labels that each got.

#379 _cli: add `sigstore verify identity`
  .github/workflows/ci.yml
  Makefile
  README.md
  sigstore/_cli.py
Labels: component:cli, refactoring, safe to test

#387 pyproject: constrain ruff
  .github/dependabot.yml
  pyproject.toml
Labels: component:cicd, chore, safe to test

#391 workflows: move linting to a separate workflow
  .github/workflows/ci.yml
  .github/workflows/lint.yml
Labels: component:cicd, chore, safe to test

#396 workflows: use pip cache
  .github/workflows/ci.yml
  .github/workflows/conformance.yml
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/release.yml
  .github/workflows/staging-tests.yml
Labels: component:cicd, chore, safe to test

#389 CHANGELOG: change catchup
  CHANGELOG.md
Labels: documentation, chore, safe to test

#383 sign, verify: Expose sign and verify as importable modules
  CHANGELOG.md
  README.md
  pyproject.toml
  sigstore/_cli.py
  sigstore/_internal/merkle.py
  sigstore/_internal/oidc/__init__.py
  sigstore/_internal/oidc/ambient.py
  sigstore/_internal/oidc/issuer.py
  sigstore/_internal/oidc/oauth.py
  sigstore/_internal/rekor/__init__.py
  sigstore/_internal/rekor/client.py
  sigstore/_internal/set.py
  sigstore/oidc.py
  sigstore/rekor.py
  sigstore/sign.py
  sigstore/verify/__init__.py
  sigstore/verify/models.py
  sigstore/verify/policy.py
  sigstore/verify/verifier.py
  test/unit/conftest.py
  test/unit/internal/oidc/test_ambient.py
  test/unit/internal/oidc/test_issuer.py
  test/unit/internal/rekor/test_client.py
  test/unit/test_sign.py
  test/unit/verify/test_models.py
  test/unit/verify/test_policy.py
  test/unit/verify/test_verifier.py
Labels: component:api

#381 CLI: `sigstore verify github`
  CHANGELOG.md
  Makefile
  README.md
  sigstore/_cli.py
Labels: component:cli, safe to test

#398 Prep 0.10.0
  CHANGELOG.md
  sigstore/__init__.py
Labels: chore

#390 TASK(jl): increase code coverage deux
  test/unit/assets/bad.txt
  test/unit/assets/bad.txt.crt
  test/unit/assets/bad.txt.sig
  test/unit/internal/fulcio/test_client.py
  test/unit/internal/test_ctfe.py
  test/unit/internal/test_sct.py
  test/unit/internal/test_tuf.py
  test/unit/test_sign.py
  test/unit/test_utils.py
  test/unit/verify/test_models.py
  test/unit/verify/test_verifier.py
Labels: component:tests

#402 API: Remove unnecessary jargon
  .github/workflows/docs.yml
  CONTRIBUTING.md
  Makefile
  README.md
  pyproject.toml
  sigstore/_cli.py
  sigstore/_internal/merkle.py
  sigstore/_internal/rekor/client.py
  sigstore/_internal/set.py
  sigstore/sign.py
  sigstore/transparency.py
  sigstore/verify/models.py
  test/unit/internal/rekor/test_client.py
Labels: documentation, component:api, safe to test

#400 workflows: upgrade `sigstore` CLI patterns
  .github/workflows/release.yml
  .github/workflows/scorecards-analysis.yml
  .github/workflows/staging-tests.yml
Labels: component:cicd, chore

#405 docs: Documentation tweaks
  README.md
  sigstore/__init__.py
  sigstore/verify/__init__.py
Labels: documentation, component:cicd

#409 workflows: Simplify documentation deployment workflow
  .github/workflows/docs.yml
Labels: documentation, component:cicd

#412 README: ToC, cleanup
  README.md
Labels: documentation, chore, safe to test

#413 CHANGELOG: catchup
  CHANGELOG.md
Labels: documentation, chore, safe to test

#414 sigstore: `RekorEntryMissing` -> `LogEntryMissing`
  CHANGELOG.md
  sigstore/_cli.py
  sigstore/verify/__init__.py
  sigstore/verify/verifier.py
Labels: component:api

#424 pyproject: add API documentation link to metadata
  pyproject.toml
Labels: documentation, chore, safe to test

#427 sigstore: 1.0.0rc1
  sigstore/__init__.py
Labels: chore, safe to test

#432 sigstore, test: relax timeout on TUF retrieval
  CHANGELOG.md
  sigstore/_internal/tuf.py
  test/unit/conftest.py
Labels: safe to test, component:tuf

#433 Makefile, ci: test Windows, accomodations
  .gitattributes
  .github/workflows/ci.yml
  .github/workflows/lint.yml
  Makefile
  test/unit/conftest.py
  test/unit/internal/test_tuf.py
Labels: component:cicd, plat:windows, plat:macos

#448 pyproject: bump pyOpenSSL >= 23.0.0
  CHANGELOG.md
  pyproject.toml
Labels: dependencies

#465 Initial Sigstore bundle support
  .gitignore
  README.md
  pyproject.toml
  sigstore/_cli.py
  sigstore/sign.py
Labels: component:cli, component:signing, safe to test

#470 CHANGELOG: record changes
  CHANGELOG.md
Labels: documentation, chore, safe to test

#471 pyproject: semver match for tuf dep
  pyproject.toml
Labels: dependencies, chore, safe to test

#477 pyproject.toml: Don't check for line-length with `ruff` since we're reformatting with `black`
  pyproject.toml
Labels: refactoring, safe to test

#478 Support verifying Sigstore bundles
  CHANGELOG.md
  README.md
  sigstore/_cli.py
  sigstore/_internal/rekor/client.py
  sigstore/transparency.py
  sigstore/verify/__init__.py
  sigstore/verify/models.py
  sigstore/verify/verifier.py
  test/unit/assets/bundle.txt
  test/unit/assets/bundle.txt.sigstore
  test/unit/assets/bundle_no_cert.txt
  test/unit/assets/bundle_no_cert.txt.sigstore
  test/unit/assets/bundle_no_log_entry.txt
  test/unit/assets/bundle_no_log_entry.txt.sigstore
  test/unit/assets/example.bundle
  test/unit/assets/offline-rekor.txt.rekor
  test/unit/conftest.py
  test/unit/internal/rekor/test_client.py
  test/unit/verify/test_models.py
  test/unit/verify/test_verifier.py
Labels: component:cli, component:verification

#485 Conformance suite fixes
  .github/workflows/conformance.yml
  sigstore/_cli.py
Labels: component:cicd, component:tests

#484 Prep 1.1.0
  CHANGELOG.md
  sigstore/__init__.py
Labels: chore, safe to test
