Repository sigstore/sigstore-python, pull requests merged in 2023-06, with the labels that each got.

#673 sign: switch another keysite to P-256
  sigstore/sign.py
Labels: component:signing, component:api

#667 feat: Add `--oauth-force-oob` CLI option
  CHANGELOG.md
  README.md
  sigstore/_cli.py
  sigstore/oidc.py
  test/unit/internal/oidc/test_issuer.py
Labels: component:cli, component:signing, component:api

#674 Handle the case of missing EKU in _is_preissuer
  CHANGELOG.md
  sigstore/_internal/sct.py
  sigstore/_utils.py
  test/unit/test_utils.py
Labels: component:signing

#694 don't parse error messages as json
  CHANGELOG.md
  sigstore/_internal/rekor/client.py
Labels: component:api
