Repository sigstore/sigstore-python, pull requests merged in 2023-07, with the labels that each got.

#701 Add timezone (utc) info into the cert not_valid_after field
  sigstore/sign.py
Labels: component:signing, component:api

#713 sigstore: 2.0.0rc2
  sigstore/__init__.py
Labels: chore

#720 conformance: bump runner
  test/integration/sigstore-python-conformance
Labels: component:tests
