Repository sigstore/sigstore-python, pull requests merged in 2023-08, with the labels that each got.

#723 models: require checkpoint in embedded inclusion proof
  .github/workflows/conformance.yml
  sigstore/transparency.py
  sigstore/verify/models.py
  sigstore/verify/verifier.py
Labels: component:verification

#745 Drop support for Python 3.7
  .github/workflows/ci.yml
  .github/workflows/lint.yml
  .github/workflows/requirements.yml
  CONTRIBUTING.md
  README.md
  pyproject.toml
Labels: dependencies

#746 Update securityscorecards.dev URL
  README.md
Labels: chore

#747 CHANGELOG: record #745
  CHANGELOG.md
Labels: chore

#753 pin-requirements: explicitly fetch tags
  .github/workflows/pin-requirements.yml
Labels: component:cicd

#717 Update comments
  sigstore/_utils.py
  sigstore/sign.py
Labels: chore
