Repository sigstore/sigstore-python, pull requests merged in 2023-05, with the labels that each got.

#641 sigstore: fix `detect_credential` signature
  CHANGELOG.md
  sigstore/_cli.py
  sigstore/oidc.py
Labels: component:api

#642 cli: Remove default subcommand hack
  CHANGELOG.md
  README.md
  sigstore/_cli.py
  test/integration/sigstore-python-conformance
Labels: component:cli, refactoring, chore

#634 Root hash signature verification v2
  CHANGELOG.md
  sigstore/_internal/rekor/__init__.py
  sigstore/_internal/rekor/checkpoint.py
  sigstore/_internal/set.py
  sigstore/sign.py
  sigstore/transparency.py
  sigstore/verify/models.py
  sigstore/verify/verifier.py
  test/unit/assets/bundle.txt.crt
  test/unit/assets/bundle.txt.sig
  test/unit/assets/bundle.txt.sigstore
  test/unit/assets/bundle_no_checkpoint.txt
  test/unit/assets/bundle_no_checkpoint.txt.bundle
  test/unit/assets/bundle_no_checkpoint.txt.crt
  test/unit/assets/bundle_no_checkpoint.txt.sigstore
  test/unit/internal/rekor/test_client.py
  test/unit/verify/test_models.py
  test/unit/verify/test_verifier.py
Labels: enhancement, component:verification, component:api

#635 sigstore: refactor, use IdentityToken everywhere
  CHANGELOG.md
  sigstore/_cli.py
  sigstore/_internal/fulcio/client.py
  sigstore/_internal/oidc/__init__.py
  sigstore/oidc.py
  sigstore/sign.py
  test/unit/conftest.py
  test/unit/test_oidc.py
  test/unit/test_sign.py
Labels: component:signing, refactoring
