Repository sigstore/sigstore-python, pull requests merged in 2024-04, with the labels that each got.

#937 Remove VerificationMaterials (take 2)
  CHANGELOG.md
  sigstore/_cli.py
  sigstore/_internal/merkle.py
  sigstore/_internal/rekor/__init__.py
  sigstore/_internal/rekor/checkpoint.py
  sigstore/_internal/set.py
  sigstore/sign.py
  sigstore/transparency.py
  sigstore/verify/__init__.py
  sigstore/verify/models.py
  sigstore/verify/verifier.py
  test/unit/assets/bundle.txt.sigstore
  test/unit/assets/bundle_cve_2022_36056.txt
  test/unit/assets/bundle_cve_2022_36056.txt.sigstore
  test/unit/assets/bundle_invalid_version.txt
  test/unit/assets/bundle_invalid_version.txt.sigstore
  test/unit/assets/bundle_no_cert.txt.sigstore
  test/unit/assets/bundle_no_cert_v1.txt
  test/unit/assets/bundle_no_cert_v1.txt.sigstore
  test/unit/conftest.py
  test/unit/test_sign.py
  test/unit/test_transparency.py
  test/unit/verify/test_models.py
  test/unit/verify/test_policy.py
  test/unit/verify/test_verifier.py
Labels: component:verification, component:api

#944 CHANGELOG: backport 2.1.3 CL
  CHANGELOG.md
Labels: chore

#952 Bump protobuf-specs, handle v3 media types
  pyproject.toml
  sigstore/_utils.py
  sigstore/verify/models.py
  test/unit/assets/bundle_cve_2022_36056.txt.sigstore
  test/unit/assets/bundle_v3.txt
  test/unit/assets/bundle_v3.txt.sigstore
  test/unit/assets/bundle_v3_alt.txt
  test/unit/assets/bundle_v3_alt.txt.sigstore
  test/unit/verify/test_verifier.py
Labels: enhancement

#953 sigstore, test: honor PublicKeyDetails when loading Keyrings
  sigstore/_internal/trustroot.py
  sigstore/_utils.py
  test/unit/internal/test_ctfe.py
  test/unit/internal/test_trust_root.py
  test/unit/test_utils.py
Labels: refactoring

#955 sigstore: rename more logger instances
  sigstore/_cli.py
  sigstore/_internal/fulcio/client.py
  sigstore/_internal/oidc/oauth.py
  sigstore/_internal/rekor/client.py
  sigstore/_internal/sct.py
  sigstore/_internal/tuf.py
Labels: chore

#956 sigstore, test: break apart DSSE/artifact sign APIs
  CHANGELOG.md
  sigstore/_cli.py
  sigstore/sign.py
  test/unit/test_sign.py
Labels: refactoring

#962 Initial DSSE verify APIs
  sigstore/_cli.py
  sigstore/_internal/rekor/__init__.py
  sigstore/dsse.py
  sigstore/verify/models.py
  sigstore/verify/verifier.py
  test/unit/assets/bundle_cve_2022_36056.txt
  test/unit/assets/bundle_cve_2022_36056.txt.sigstore
  test/unit/test_sign.py
  test/unit/verify/test_verifier.py
Labels: component:verification, refactoring

#972 rename sign_intoto -> sign_dsse
  CHANGELOG.md
  sigstore/sign.py
  test/unit/test_sign.py
  test/unit/verify/test_verifier.py
Labels: component:signing, component:api, refactoring

#981 bump sigstore-rekor-types, add NOTE
  pyproject.toml
  sigstore/sign.py
Labels: dependencies

#992 sigstore: extract LogEntry conversions to their own functions
  sigstore/models.py
  test/unit/test_models.py
Labels: enhancement
