Repository sigstore/sigstore-python, pull requests merged in 2024-10, with the labels that each got.

#1152 _cli: files always take precedence over digests
  CHANGELOG.md
  sigstore/_cli.py
Labels: component:cli

#1154 pyproject: fix status classifier
  pyproject.toml
Labels: chore

#1163 bump minimum Python to 3.9
  .github/workflows/ci.yml
  .github/workflows/lint.yml
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  pyproject.toml
  test/integration/cli/test_sign.py
Labels: chore

#1170 workflows/requirements: remove a lingering 3.8 reference
  .github/workflows/requirements.yml
Labels: component:cicd, chore

#1174 _cli: add `plumbing update-trust-root`
  CHANGELOG.md
  sigstore/_cli.py
Labels: component:cli

#1179 _cli: don't warn on bare .sigstore if cert/sig is used
  sigstore/_cli.py
Labels: component:cli

#1184 Prep 3.5.0
  CHANGELOG.md
  sigstore/__init__.py
Labels: chore

#1192 _cli: fix warning check
  CHANGELOG.md
  sigstore/_cli.py
Labels: bug, component:cli

#1200 Add CertificateAuthority
  sigstore/_internal/trust.py
  test/assets/trusted_root/certificate_authority.empty.json
  test/assets/trusted_root/certificate_authority.json
  test/unit/internal/test_trust.py
Labels: component:verification, component:tuf
