Repository sigstore/sigstore-python, pull requests merged in 2024-03, with the labels that each got.

#910 Adding sct verification for certificates on verify flow
  sigstore/_cli.py
  sigstore/_internal/fulcio/client.py
  sigstore/_internal/sct.py
  sigstore/_internal/trustroot.py
  sigstore/verify/verifier.py
  test/unit/internal/test_trust_root.py
Labels: component:verification, component:api

#904 sigstore: prep verify APIs for DSSE
  CHANGELOG.md
  sigstore/_cli.py
  sigstore/_utils.py
  sigstore/verify/models.py
  sigstore/verify/verifier.py
  test/unit/conftest.py
  test/unit/test_sign.py
  test/unit/verify/test_models.py
  test/unit/verify/test_policy.py
  test/unit/verify/test_verifier.py
Labels: component:verification, component:api

#921 sigstore/sign: sign API takes bytes, not I/O
  CHANGELOG.md
  sigstore/_cli.py
  sigstore/_utils.py
  sigstore/sign.py
  sigstore/verify/verifier.py
  test/unit/test_sign.py
  test/unit/test_utils.py
  test/unit/verify/test_models.py
  test/unit/verify/test_verifier.py
Labels: component:signing, component:api

#924 verifier: set store flags explicitly
  sigstore/verify/verifier.py
Labels: component:verification, component:api

#930 sigstore: use our own Statement type
  CHANGELOG.md
  pyproject.toml
  sigstore/_internal/dsse.py
  sigstore/_internal/rekor/client.py
  sigstore/dsse.py
  sigstore/sign.py
  sigstore/verify/models.py
  sigstore/verify/policy.py
  sigstore/verify/verifier.py
  test/unit/test_sign.py
  test/unit/verify/test_policy.py
Labels: component:signing, component:api

#936 Key management improvement
  CHANGELOG.md
  README.md
  sigstore/_cli.py
  sigstore/_internal/ctfe.py
  sigstore/_internal/keyring.py
  sigstore/_internal/rekor/checkpoint.py
  sigstore/_internal/rekor/client.py
  sigstore/_internal/sct.py
  sigstore/_internal/set.py
  sigstore/_internal/trustroot.py
  sigstore/sign.py
  sigstore/verify/verifier.py
  test/unit/internal/test_ctfe.py
  test/unit/internal/test_trust_root.py
  test/unit/test_sign.py
  test/unit/verify/test_models.py
Labels: component:signing, component:verification
