Repository sigstore/sigstore-python, pull requests merged in 2024-05, with the labels that each got.

#997 test_sign: disable more staging tests
  .github/workflows/ci.yml
  test/unit/conftest.py
Labels: component:cicd, component:tests

#998 sigstore: 3.0.0rc1
  sigstore/__init__.py
Labels: chore

#1004 sigstore: add new verification policies for missing extensions
  pyproject.toml
  sigstore/verify/policy.py
  test/unit/assets/bundle_v3_github.whl
  test/unit/assets/bundle_v3_github.whl.sigstore
  test/unit/verify/test_policy.py
Labels: component:verification, component:api

#1003 sigstore: add `py.typed` marker for type checking
  sigstore/py.typed
Labels: enhancement, component:api

#1013 bump sigstore-protobuf-specs
  pyproject.toml
  sigstore/_internal/trustroot.py
  sigstore/dsse.py
  sigstore/models.py
Labels: refactoring, chore

#1016 oidc: rename expected_certificate_subject -> federated_issuer
  CHANGELOG.md
  sigstore/oidc.py
  test/unit/test_oidc.py
Labels: component:api

#1015 cli: allow DSSE verification
  CHANGELOG.md
  README.md
  sigstore/_cli.py
  sigstore/dsse.py
  sigstore/hashes.py
  sigstore/verify/policy.py
Labels: component:cli, component:verification

#1010 Refactor client trust/trust root management
  CHANGELOG.md
  README.md
  sigstore/_cli.py
  sigstore/_internal/rekor/checkpoint.py
  sigstore/_internal/sct.py
  sigstore/_internal/trust.py
  sigstore/models.py
  sigstore/sign.py
  sigstore/verify/verifier.py
  test/unit/assets/trust_config/config.badtype.json
  test/unit/assets/trust_config/config.v1.json
  test/unit/assets/trusted_root/trustedroot.badtype.json
  test/unit/assets/trusted_root/trustedroot.v1.json
  test/unit/internal/test_trust.py
  test/unit/test_sign.py
Labels: component:signing, component:verification, component:api, refactoring

#1020 README: improve `verify github` examples
  README.md
Labels: documentation

#1021 sigstore: 3.0.0
  CHANGELOG.md
  sigstore/__init__.py
Labels: chore

#1025 release: remove pip cache usage
  .github/workflows/release.yml
Labels: component:cicd
