Repository sigstore/sigstore-python, pull requests merged in 2024-11, with the labels that each got.

#1186 Add models for TimestampVerificationData
  pyproject.toml
  sigstore/models.py
  test/unit/test_models.py
Labels: component:verification, component:api

#1206 Timestamp Authority Verification
  CHANGELOG.md
  sigstore/_internal/timestamp.py
  sigstore/models.py
  sigstore/verify/verifier.py
  test/assets/trusted_root/certificate_authority.missingroot.json
  test/assets/tsa/bundle.duplicate.sigstore
  test/assets/tsa/bundle.many_timestamp.sigstore
  test/assets/tsa/bundle.txt
  test/assets/tsa/bundle.txt.sigstore
  test/assets/tsa/ca.json
  test/unit/verify/test_verifier.py
Labels: enhancement

#1222 pyproject: bump sigstore-rekor-types
  pyproject.toml
Labels: dependencies

#1216 Sign Bundle with a Timestamp Authority
  .github/workflows/ci.yml
  sigstore/_internal/timestamp.py
  sigstore/models.py
  sigstore/sign.py
  sigstore/verify/verifier.py
  test/assets/tsa/trust_config.json
  test/conftest.py
  test/unit/conftest.py
  test/unit/internal/test_timestamping.py
  test/unit/test_sign.py
  test/unit/verify/test_verifier.py
Labels: component:signing, component:api

#1224 CHANGELOG: record #1216
  CHANGELOG.md
Labels: chore
