Repository sigstore/sigstore-python, pull requests merged in 2024-09, with the labels that each got.

#1116 Print in-toto statement when verifying DSSE
  CHANGELOG.md
  sigstore/_cli.py
Labels: component:cli, component:verification

#1120 Add support for Python 3.13
  .github/workflows/ci.yml
  .github/workflows/requirements.yml
  pyproject.toml
Labels: chore

#1134 Add CLI integration tests for sign subcommand
  test/integration/cli/test_sign.py
Labels: component:tests

#1143 cli: --offline means fully offline
  CHANGELOG.md
  README.md
  sigstore/_cli.py
  sigstore/_internal/tuf.py
  sigstore/verify/verifier.py
  test/unit/verify/test_verifier.py
Labels: component:cli, component:verification

#1145 workflows/release: enable PEP 740 attestations
  .github/workflows/release.yml
Labels: component:cicd, chore
