Repository sigstore/sigstore-python, pull requests merged in 2024-01, with the labels that each got.

#855 dependabot: group GHA updates
  .github/dependabot.yml
Labels: component:cicd, chore

#844 Separate TUF and trusted root management code
  sigstore/_cli.py
  sigstore/_internal/rekor/client.py
  sigstore/_internal/trustroot.py
  sigstore/_internal/tuf.py
  sigstore/sign.py
  sigstore/verify/verifier.py
  test/unit/conftest.py
  test/unit/internal/test_trust_root.py
  test/unit/verify/test_models.py
Labels: enhancement, component:tuf

#862 API: remove SigningResult
  CHANGELOG.md
  pyproject.toml
  sigstore/_cli.py
  sigstore/_utils.py
  sigstore/sign.py
  sigstore/verify/verifier.py
  test/unit/conftest.py
  test/unit/test_sign.py
Labels: component:signing, component:api

#804 API-level DSSE signing support
  CHANGELOG.md
  pyproject.toml
  sigstore/_internal/dsse.py
  sigstore/_internal/rekor/client.py
  sigstore/sign.py
  sigstore/verify/models.py
Labels: component:signing, component:api, upstream, blocked

#860 feat: Enable signing with pre-computed hash
  CHANGELOG.md
  sigstore/_utils.py
  sigstore/hashes.py
  sigstore/sign.py
  sigstore/verify/models.py
  sigstore/verify/verifier.py
  test/unit/conftest.py
  test/unit/test_sign.py
Labels: component:signing, component:api

#875 Fix interrogate usage, clean up linting
  .github/workflows/lint.yml
  pyproject.toml
Labels: component:cicd, chore
